---
# tasks file for web-server
- name: install httpd
  yum:
    name: httpd
    state: present
    
- name: httpd template for index.html
  template:
    src: index.html.j2 
    dest: /var/www/html/index.html
    mode: 0644
  notify: restart httpd

# - name: install nginx
#   yum:
#     name: nginx
#     state: present